# 스프링 부트 서버가 실행되면 자동으로 로딩되는 파일
# 데이터베이스의 설정 정보, 로깅 설정 정보 등이 들어갈 수 있고, 직접 설정을 정의할 때 사용
server:
  port: 80

spring:
  h2:
    console:
      enabled: true # /h2-console 설정
  datasource:
    url: jdbc:h2:mem:testdb # 메모리 H2 DB 경로 설정
  jpa:
    show-sql: true # 전송 쿼리 확인, 애플리케이션 실행과정에 쿼리의 실행 구문을 모두 보여줌
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
  devtools:
    livereload:
      enabled: true # 파일(특히 정적 리소스나 템플릿)이 변경되면 livereload 서버가 브라우저에 변경을 감지하도록 신호를 보내어 자동으로 새로고침되게 함
    restart:
      enabled: false # Java 클래스 변경에 따른 애플리케이션 자동 재시작을 제어하는 옵션
  thymeleaf:
    cache: false # 템플릿을 수정할 때마다 변경 사항이 바로 반영되도록 캐싱 비활성화